### ISSUE TITLE
Not Able to Add K9 RPMs to GISO

### ISSUE THREAD

**Issue by joseroane** [ios-xr/gisobuild#58]
Hi I'm currently trying to build multiple golden ISOs for 540L devices (XR 7.5.2, 7.9.1 and 7.10.2), I'm not filtering any packages and yet the k9sec optional-packages are not being added to the GISO. How can I fix this ? Below is an example of what I've been doing 

YAML File
```
packages:
    iso: ~/network_os/NCS540L/xr_7_9_1/ncs540l-x64-7.9.1.iso
    repo: 
        - ~/network_os/NCS540L/xr_7_9_1/rpms
    pkglist: []
    bridge-fixes:
        upgrade-from-release:
        rpms:
    remove_packages:

user-content:
    script:
    xrconfig:

output:
    label:
    out-directory: ~/network_os/NCS540L/xr_7_9_1/giso
    clean: true

options:
    docker: false
    migration: false
    x86-only: false
```
Verification
```
~/gisobuild$ sudo ./src/lntmod/isols.py -i ~/network_os/NCS540L/xr_7_9_1/giso/giso/ncs540l-golden-x86_64-7.9.1-0.iso --optional-packages
Group: main
  xr-bgp
  xr-ipsla
  xr-is-is
  xr-lldp
  xr-mcast
  xr-mpls-oam
  xr-ncs540l-mcast
  xr-ncs540l-netflow
  xr-netflow
  xr-ospf
  xr-perf-meas
  xr-perfmgmt
  xr-track
```
I changed the permissions of the k9sec files as per this guide: https://www.cisco.com/c/en/us/td/docs/iosxr/ncs5500/system-setup/79x/b-system-setup-cg-ncs5500-79x/m-golden-iso.html, didn't work either, so I just matched them with the bgp rpms.

The k9sec permissions match the same permissions as in the bgp rpms

```
~/network_os/NCS540L/xr_7_9_1/rpms/optional-rpms/bgp$ ls -l
total 3940
-rw-r--r-- 1 user user    5985 Apr  2  2023 xr-bgp-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user 3957258 Apr  2  2023 xr-bgp-c335acdb0a3141f0-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user    6005 Apr  2  2023 xr-bgp-n540-12z20g-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user    6037 Apr  2  2023 xr-bgp-n540-24q8l2dd-sys-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user    5997 Apr  2  2023 xr-bgp-n540-28z4c-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user    6005 Apr  2  2023 xr-bgp-n540-fh-agg-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user    6005 Apr  2  2023 xr-bgp-n540-fh-csr-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user    6013 Apr  2  2023 xr-bgp-n540x-12z16g-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user    6029 Apr  2  2023 xr-bgp-n540x-16z4g8q2c-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user    6013 Apr  2  2023 xr-bgp-n540x-16z8q2c-7.9.1v1.0.0-1.x86_64.rpm


~/network_os/NCS540L/xr_7_9_1/rpms/k9sec$ ls -l
total 1148
-rw-r--r-- 1 user user    6001 Apr  2  2023 xr-k9sec-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user 1097740 Apr  2  2023 xr-k9sec-c335acdb0a3141f0-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user    6025 Apr  2  2023 xr-k9sec-n540-12z20g-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user    6057 Apr  2  2023 xr-k9sec-n540-24q8l2dd-sys-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user    6013 Apr  2  2023 xr-k9sec-n540-28z4c-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user    6025 Apr  2  2023 xr-k9sec-n540-fh-agg-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user    6025 Apr  2  2023 xr-k9sec-n540-fh-csr-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user    6029 Apr  2  2023 xr-k9sec-n540x-12z16g-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user    6049 Apr  2  2023 xr-k9sec-n540x-16z4g8q2c-7.9.1v1.0.0-1.x86_64.rpm
-rw-r--r-- 1 user user    6033 Apr  2  2023 xr-k9sec-n540x-16z8q2c-7.9.1v1.0.0-1.x86_64.rpm
```
